---
- name: create kube addon directory
  file:
    name: "{{ kube_addon_dir }}"
    state: directory
    mode: 0755

- name: create etcd addon directory
  file:
    name: "{{ kube_addon_dir }}/kube_etcd"
    state: directory
    mode: 0755

- name: pull etcd cert base64
  slurp:
    src: "{{ etcd_cert_dir }}/{{ certs_item }}"
  with_items:
    - client.pem
    - client-key.pem
    - ca.pem
  loop_control:
    loop_var: certs_item
  register: encoded_results
  run_once: true

- name: create etcd cert secret yaml
  template:
    src: "kube_etcd_secrets.yaml"
    dest: "{{ kube_addon_dir }}/kube_etcd/kube_etcd_secrets.yaml"
    mode: 0755

- block:
  - name: kubectl create etcd cert secret
    shell: "kubectl apply -f {{ kube_addon_dir }}/kube_etcd/kube_etcd_secrets.yaml"
    register: result
    until: result.rc == 0
    retries: "{{ retries }}"
    delay: "{{ delay }}"

  - name: check etcd secrets
    shell: "kubectl get secrets --all-namespaces | grep etcd-backup-secrets"
    register: result
    until: result.rc == 0
    retries: "{{ retries }}"
    delay: "{{ delay }}"  
  run_once: true