---
- name: hostname
  shell: hostname
  register: node_hostname_cmd

- name: register hostname
  set_fact:
    node_hostname: "{{ node_hostname_cmd.stdout }}"
# todo: 更新/写入 /etc/host文件

# network
- block:
    - name: set forward accept
      shell: "iptables -p {{ item }}"
      with_items:
        - "INPUT ACCEPT" # 开放接入端
        - "OUTPUT ACCEPT" # 开放输出端
        - "FORWARD ACCEPT" # 开放中转端

# kernel module
- block:
    - name: modprobe system module
      shell: "modprobe {{ item }}"
      with_items:
        - "ip_vs"
        - "ip_vs_rr"
        - "ip_vs_wrr"
        - "ip_vs_sh"
        - "fuse"
        - "rbd"

    - name: create module files
      copy:
        src: "system.modules"
        dest: "/etc/sysconfig/modules/ip_vs.modules"
        owner: "root"
        group: "root"
        mode: 0755
# yum repo
- block:
    - name: create yum repo
      include_role:
        name: yum_service
# todo: registry

#todo: docker

- block:
    - name: install docker
      include_role:
        name: docker
#todo: create ssh key and distribute ssh key

- block:
    - name: create and distribute ssh key
      include_role:
        name: tools
        tasks_from: create_distribution_ssh_key.yaml
      vars:
      host_list: "{{ groups['node'] }}"

    - name: create and distribute cert files
      include_role:
        name: tools
        tasks_from: create_distribution_cert.yaml
      when: inventory_hostname in groups['node']
