apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-etcd
  name: kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    component: etcd
    tier: control-plane
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379