---
- name: create kube config directory
  file:
    name: "{{ kube_config_dir }}"
    state: directory
    mode: 0755

- name: create kubeconfig file
  template:
    src: "kubeletconfig.j2"
    dest: "{{ kube_config_dir }}/kubeconfig"
  vars:
    host_ip: "master.bocloud.com"
    host_port: "{{ apiserver_src_port }}"

- name: create kubeconfig file
  template:
    src: "kubeletconfig.j2"
    dest: "{{ kube_config_dir }}/kubeconfig"
  vars:
    host_ip: "127.0.0.1"
    host_port: "{{ apiserver_src_port }}"
  when: inventory_hostname in groups['kubernetes_master'] | intersect(groups['kubernetes_node'])


- name: start kubelet service
  include_tasks: install_kubelet.yaml

# todo 分发证书, 配置权限 