---
- name: create kube config directory
  file:
    name: "{{ kube_config_dir }}"
    state: directory
    mode: 0755

- name: create kubelet service script
  template:
    src: "kubelet.sh.j2"
    dest: "{{ kube_config_dir }}/kubelet.sh"
    mode: 0755

- name: create kubelet config file
  template:
    src: "kubeletconfig.j2"
    dest: "{{ kube_config_dir }}/kubeletconfig"
    mode: 0755

# todo runtime docker/containerd
- name: start kubelet service
  shell: "bash {{ kube_config_dir }}/kubelet.sh -a start -r docker"
