---
- name: create kube config directory
  file:
    name: "{{ kube_config_dir }}"
    state: directory
    mode: 0755

- name: create kubeconfig for kubenetes_node
  template: 
    src: "kubeconfig.j2" 
    dest: "{{ kube_config_dir }}/kubeconfig"
  vars:
    host_ip: "master.bocloud.com"
    host_port: "{{ apiserver_dest_port }}"
  when: inventory_hostname in groups['kubernetes_node']

- name: create kubeconfig for kubernetes_master
  template:
    src: "kubeletconfig.j2"
    dest: "{{ kube_config_dir }}/kubeconfig"
  vars:
    host_ip: "127.0.0.1"
    host_port: "{{ apiserver_src_port }}"
  when: inventory_hostname in groups['kubernetes_master']


# - name: create kubeconfig
#   template: src=kubeconfig.j2 dest={{ kube_config_dir }}/{{ file }}
#   vars:
#     host_ip: "127.0.0.1"
#     host_port: "{{ apiserver_src_port }}"
#   when: inventory_hostname in groups['kubernetes_master'] | intersect(groups['kubernetes_node'])


  