---
- name: disable chrony service
  systemd:
    name: chronyd
    enabled: no
    state: stopped

- name: yum remove chrony
  yum: 
    name: chrony 
    state: absent


- name: clean chrony config file
  file: 
    path: /etc/chrony.conf 
    state: absent
