---
# todo user and group
- name: "{{ ansible_user }} group name"
  shell: id -ng {{ ansible_user }}
  register: user_group

- name: "create ssh directory of {{ ansible_user }}"
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group.stdout }}"
    mode: 0700
    state: directory

- name: check rsa and rsa.pub file exists
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ ansible_env.HOME }}/.ssh/id_rsa"
    - "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
  register: key_file

# todo 文件存在 即判断密钥完整

- name: ssh-keygen create rsa and pub
  shell: >
    ssh-keygen -t rsa -b 2048 -N "" -C "{{ ansible_env.USER }}@{{ node_hostname }}" -f {{ ansible_env.HOME }}/.ssh/id_rsa
    creates="{{ ansible_env.HOME }}/.ssh/id_rsa"

- name: fetch keyfile from remote
  fetch:
    src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
    dest: "buffer/{{ node_hostname }}-id_rsa.pub"
    flat: yes

- name: copy key and add to authorized_keys
  authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file','buffer/{{ node_hostname }}-id_rsa.pub')}}"
  when:  item != node_hostname
  with_items: "{{ groups['nodes'] |map('extract',hostvars,'node_hostname')| list }}"

