# ---
# - name: gather_facts
#   max_fail_percentage: 0
#   hosts: all:127.0.0.1
#   tasks:
#     - name: check all hosts are reacheable
#       assert:
#         that:
#           - ansible_play_hosts == (groups['all'] + ['127.0.0.1'])
#         fail_msg: 1 or more host is UNREACHABLE
#         success_msg: ALL hosts are REACHABLE
#       run_once: yes
#     - include_vars:
#         file: ../vars/common.yaml
#     - include_vars:
#         file: ../vars/images.yaml
#     - set_fact:
#         action: deploy
---
- name: deploy
  hosts: nodes
  max_fail_percentage: 0
  become: true
  gather_facts: yes
  tasks:
    - include_vars:
        file: "{{ item }}"
      with_items:
        - "../vars/common.yaml"
        - "../vars/images.yaml"
    - set_fact:
        action: deploy

    - name: hostname
      shell: hostname
      register: node_hostname_cmd

    - name: register hostname
      set_fact:
        node_hostname: "{{ node_hostname_cmd.stdout }}"
    #add_etc_hosts
    - name: update etc hosts >
      include_role:
        name: tools
        tasks_from: add_etc_hosts.yaml


    - name: distribution of certificate
      include_role:
        name: tools
        tasks_from: create_distribution_cert.yaml



    # - name: deploy k8s node
    #   include_role:
    #     name: kubelet_service
