---
- name: deploy
  hosts: nodes
  max_fail_percentage: 0
  become: true
  gather_facts: yes
  tasks:
    - include_vars:
        file: "{{ item }}"
      with_items:
        - "common.yaml"
        - "images.yaml"
    - set_fact:
        action: "deploy"
    - name: environment
      include_role: name=environment

    - name: deploy k8s cluster
      include_role: name=k8s_core
