---
- block: 
  - name: clean runc files
    file: 
      path: "/usr/local/sbin/runc"
      state: absent

  - name: disable containerd service
    service:
      name: containerd
      enabled: no
      state: stopped
    
  - name: remove containerd rpm
    shell: "rpm -e --nodeps containerd.io"

  - name: umount kubelet pod tmpfs
    shell: "for i in $(cat /proc/mounts | grep containerd | awk '{print $2}');do umount $i;done"

  - name: clean file and directory
    file: 
      path: "{{ item }}" 
      state: absent
    with_items:
      - "/run/containerd"
      - "/etc/containerd"
      - "/var/lib/containerd"
      - "/usr/bin/containerd"
      - "/usr/bin/containerd-shim"
      - "/usr/bin/containerd-shim-runc-v1"
      - "/usr/bin/containerd-shim-runc-v2"
      - "/opt/containerd"
      - "/usr/bin/crictl"
      - "/usr/bin/ctr"
      - "nerdctl"
      - "/etc/crictl.yaml"
  ignore_errors: true